# Generated by Django 4.2.7 on 2024-01-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_complains',
            name='body',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
