# Generated by Django 4.2.7 on 2024-01-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_feedback_complains_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_complains',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
