# Generated by Django 4.2.7 on 2024-01-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_feedback_complains_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='recomandations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Level1'), ('2', 'Level2'), ('3', 'Level3'), ('4', 'Level4')], max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback_complains',
            name='reply',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
