# Generated by Django 5.0.1 on 2024-01-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0004_recomandations_alter_feedback_complains_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback_complains",
            name="reply",
            field=models.CharField(
                blank=True, default="None", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="feedback_complains",
            name="type",
            field=models.CharField(
                choices=[("Complain", "Complain"), ("Feedback", "Feedback")],
                max_length=225,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recomandations",
            name="type",
            field=models.CharField(
                choices=[
                    ("1", "Level1"),
                    ("2", "Level2"),
                    ("3", "Level3"),
                    ("4", "Level4"),
                ],
                max_length=225,
                null=True,
            ),
        ),
    ]
