# Generated by Django 4.2.7 on 2023-12-01 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(default='Not Selected', max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('accountNumber', models.CharField(max_length=200, null=True)),
                ('networkAdmin', models.BooleanField(default=False, null=True)),
                ('customer', models.BooleanField(default=False, null=True)),
                ('capacity', models.CharField(max_length=200, null=True)),
                ('IPAddress', models.CharField(max_length=100, null=True)),
                ('Network', models.CharField(choices=[('VSAT', 'VSAT'), ('Fibre', 'Fibre')], max_length=100, null=True)),
                ('Service', models.CharField(choices=[('VPN', 'VPN'), ('Internet', 'Internet')], max_length=100, null=True)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='Pictures')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personal Infomation')),
            ],
        ),
    ]
