# Generated by Django 4.2.7 on 2023-12-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_networkprofile_one_true_one_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkprofile',
            name='customer',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
