# Generated by Django 4.2.7 on 2023-12-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_networkprofile_customer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='networkprofile',
            name='one_true_one_false',
        ),
        migrations.RemoveField(
            model_name='networkprofile',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='networkprofile',
            name='networkAdmin',
        ),
    ]
