# Generated by Django 4.2.7 on 2023-12-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_networkprofile_one_true_one_false_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkprofile',
            name='Service',
            field=models.CharField(choices=[('customer', 'Customer'), ('Admin', 'Telone Admin')], max_length=100, null=True),
        ),
    ]
