# Generated by Django 5.0.1 on 2024-02-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_networkprofile_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkprofile",
            name="IPAddress",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="networkprofile",
            name="Network",
            field=models.CharField(
                blank=True,
                choices=[("VSAT", "VSAT"), ("Fibre", "Fibre")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="networkprofile",
            name="Service",
            field=models.CharField(
                blank=True,
                choices=[("customer", "Customer"), ("Admin", "GNP Admin")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="networkprofile",
            name="capacity",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
