# Generated by Django 5.0.1 on 2024-02-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_networkprofile_ipaddress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkprofile",
            name="phoneNumber",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
